apiVersion: v1
kind: Secret
metadata:
  name: mongodb
type: Opaque
data:
  database-user: bW9uZ29kb29kbGU=
  database-password: bW9uZ29kb29kbGU=
  database-admin-password: bW9uZ29kb29kbGU=
  database-name: bW9uZ29kb29kbGU=
