apiVersion: v1
kind: Secret
metadata:
  name: mattermost-penfold-config
type: Opaque
data:
  mongohost: aHR0cDovL3h4LXl5eXknLmNvbS9rZmxhanNmbAo=
  mongouser: aHR0cDovL3h4LXl5eXknLmNvbS9rZmxhanNmbAo=
  mongopassword: aHR0cDovL3h4LXl5eXknLmNvbS9rZmxhanNmbAo=
  mattermosthost: aHR0cDovL3h4LXl5eXknLmNvbS9rZmxhanNmbAo=
  mattermostgroup: aHR0cDovL3h4LXl5eXknLmNvbS9rZmxhanNmbAo=
  mattermostuser: aHR0cDovL3h4LXl5eXknLmNvbS9rZmxhanNmbAo=
  mattermostpassword: aHR0cDovL3h4LXl5eXknLmNvbS9rZmxhanNmbAo=
